language: elixir
elixir:
  - 1.2.6
  - 1.3.4
  - 1.4.2
otp_release:
  - 18.3
  - 19.2
before_script: MIX_ENV=test mix compile --warnings-as-errors
script: mix coveralls.travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
