version: build{build}

install:
  - cinst elixir
  - refreshenv

shallow_clone: true

build_script:
  - mix local.hex --force
  - mix deps.get
  - mix local.rebar --force
  - mix compile --warnings-as-errors

test_script:
  - mix test
